# This is a basic workflow that is manually triggered

name: GET OFF DAYS

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  schedule: 
    - cron: '0 0 1 1 *'
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
   build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: pnpm/action-setup@v2
      with:
        version: 8
    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: '>=18'
        cache: 'pnpm'
    - name: Install dependecies
      run: pnpm install
    - name: GET OFF DAYS
      run: pnpm run scrape
    - name: Commit files
      run: |
        git config user.name "${{ secrets.MY_NAME }}"
        git config user.email "${{ secrets.MY_EMAIL }}"
        git add .
        git commit -m "chore: updated scraping data" -a
    - name: Push changes
      uses: ad-m/github-push-action@main
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
